/* ---------------------------------
fetchData
--------------------------------- */

import { call, put, takeEvery, select } from "redux-saga/effects";
import {
  showNotif,
  fetchData,
  // fetchDataPending,
  // fetchDataError,
  // fetchDataSuccess,
} from "../redux/actions";
import { db } from "../index";
import { IInitialState } from "../redux/initialState";
import { log } from "../utils";

function* fetchDataSaga(action) {
  const authSelector = (state: IInitialState) => state.authentication;
  const {
    user: { uid },
  } = yield select(authSelector);

  // yield put(fetchDataPending());

  try {
    const context = db.ref("/bookmarks");

    const data = yield call(
      {
        context,
        fn: context.once,
      },
      "value"
    );

    log("@@@", data, data.val());

    // this is the key generated by firebase
    // yield put(fetchDataSuccess(updates));

    // yield put(
    //   showNotif({
    //     message: `Created new tag!`,
    //     icon: "star",
    //     timeOut: 2000,
    //     theme: "light",
    //   })
    // );

    //
  } catch (error) {
    //
    console.error(error);
    // yield put(fetchDataError({ error }));
  }
}

/**
 * fetchData
 */

export default function* () {
  yield takeEvery(`${fetchData}`, fetchDataSaga);
}
